### ISSUE TITLE
Request: Theme Access

### ISSUE THREAD

**Issue by nogtini** [d4nyll/epic#4]
Would love to be able to instantly change the default dark theme and import my own .css themes. I'm currently modifying the internal code to get the style I like.

**Comment by d4nyll** [comment]
Thanks for your suggestion. I will aim to implement this and #1 this week!

**Comment by d4nyll** [comment]
You can now do this by placing **all** your theme's CSS file inside the `public` directory. Then create a variable containing the options, which should include **all** the themes - i.e. If you are using a custom `editor` theme, you would also need to place the `base` and `preview` theme in the relevant directory also.

Here's an example taken from `/example/testing/`:

```
Template.epicCreate.rendered = function () {
    var opts = {    
        basePath: '/epic/themes',
        theme: {
            base: '/base/epiceditor.css',
            preview: '/preview/github.css',
            editor: '/editor/epic-custom.css'
        }
    };
    Epic.create('epicCreateContainer', opts);
};
```

Here, the `editor` CSS files are placed inside the `/public/epic/themes/editor/epic-custom.css` of the application.

Please tell me if it works for you. I will add this to the documentation soon.
